"""INT8 TFLite export of a trained CNN1D and the C header for the firmware.

Path: PyTorch weights -> equivalent Keras model -> TFLite full-integer quantization
(post-training, calibrated on training windows) -> `.tflite` + `const unsigned char[]` header.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import torch

from . import WINDOW_SAMPLES
from .models import CONV_SPECS, CNN1D

# The firmware allocates the tensor arena statically, and TFLite Micro needs scratch space
# on top of the live activations. 1.5x the lower bound matched the measured arena of the
# thesis model (68 KB measured, 48 KB lower bound); treat it as a starting point.
ARENA_SAFETY_FACTOR = 1.5


def _tf():
    import logging
    import os

    os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")
    try:
        import tensorflow as tf
    except ImportError as exc:  # pragma: no cover
        raise ImportError("Export needs TensorFlow: pip install 'ecg2mcu[export]'") from exc
    tf.get_logger().setLevel(logging.ERROR)  # the TFLite converter is very chatty
    return tf


def build_keras_model(in_channels: int, fc_size: int, num_classes: int = 5, window: int = WINDOW_SAMPLES):
    tf = _tf()
    keras = tf.keras
    inp = keras.Input(shape=(window, in_channels), name="input")
    x = inp
    for i, (filters, kernel) in enumerate(CONV_SPECS, start=1):
        x = keras.layers.Conv1D(filters, kernel, padding="same", use_bias=False, name=f"conv{i}")(x)
        x = keras.layers.BatchNormalization(epsilon=1e-5, name=f"bn{i}")(x)  # PyTorch BatchNorm eps
        x = keras.layers.ReLU(name=f"relu{i}")(x)
        if i < len(CONV_SPECS):
            x = keras.layers.MaxPooling1D(2, name=f"pool{i}")(x)
    x = keras.layers.GlobalAveragePooling1D(name="gap")(x)
    x = keras.layers.Dense(fc_size, name="fc1")(x)
    x = keras.layers.ReLU(name="relu_fc")(x)
    x = keras.layers.Dense(num_classes, name="fc2")(x)
    return keras.Model(inp, x)


def transfer_weights(model: CNN1D, keras_model) -> float:
    """Copy PyTorch weights into the Keras model; returns the max output difference on random input."""
    sd = {k: v.detach().cpu().numpy() for k, v in model.state_dict().items()}
    for i in range(1, len(CONV_SPECS) + 1):
        keras_model.get_layer(f"conv{i}").set_weights([sd[f"conv{i}.weight"].transpose(2, 1, 0)])
        keras_model.get_layer(f"bn{i}").set_weights(
            [sd[f"bn{i}.weight"], sd[f"bn{i}.bias"], sd[f"bn{i}.running_mean"], sd[f"bn{i}.running_var"]]
        )
    keras_model.get_layer("fc1").set_weights([sd["fc1.weight"].T, sd["fc1.bias"]])
    keras_model.get_layer("fc2").set_weights([sd["fc2.weight"].T, sd["fc2.bias"]])

    rng = np.random.default_rng(0)
    probe = rng.standard_normal((8, model.in_channels, WINDOW_SAMPLES)).astype(np.float32)
    model.eval()
    with torch.no_grad():
        ref = model(torch.from_numpy(probe)).numpy()
    out = keras_model.predict(probe.transpose(0, 2, 1), verbose=0)
    return float(np.abs(ref - out).max())


def convert_int8(keras_model, calibration: np.ndarray) -> bytes:
    """Full-integer TFLite model. `calibration` has shape (N, channels, T)."""
    tf = _tf()
    cal = calibration.transpose(0, 2, 1).astype(np.float32)

    def representative_dataset():
        for i in range(len(cal)):
            yield [cal[i:i + 1]]

    converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    return converter.convert()


def c_header(model_bytes: bytes, var_name: str = "cnn1d_model") -> str:
    """C header with the model as an 8-byte aligned PROGMEM array (what TFLite Micro expects)."""
    rows = [
        "  " + ", ".join(f"0x{b:02x}" for b in model_bytes[i:i + 16])
        for i in range(0, len(model_bytes), 16)
    ]
    guard = var_name.upper() + "_H"
    return "\n".join([
        "// Generated by ecg2mcu",
        f"// Model size: {len(model_bytes)} bytes ({len(model_bytes) / 1024:.1f} KB)",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        '#include "Arduino.h"',
        "",
        f"const unsigned int {var_name}_len = {len(model_bytes)};",
        "",
        f"alignas(8) const unsigned char {var_name}[] PROGMEM = {{",
        ",\n".join(rows),
        "};",
        "",
        f"#endif // {guard}",
        "",
    ])


def estimate_memory(model_bytes: int, in_channels: int, fc_size: int, window: int = WINDOW_SAMPLES) -> dict:
    """Rough memory budget for the device (INT8 activations, 1 byte per value).

    Flash is the model size. The arena lower bound is the largest sum of a layer's input and
    output tensors; the recommendation adds a safety factor for TFLite Micro scratch buffers.
    """
    sizes = [window * in_channels]
    length = window
    for i, (filters, _) in enumerate(CONV_SPECS, start=1):
        sizes.append(length * filters)               # conv + BN + ReLU (fused)
        if i < len(CONV_SPECS):
            length //= 2
            sizes.append(length * filters)           # max pool
    sizes += [CONV_SPECS[-1][0], fc_size, 5]         # GAP, fc1, fc2
    peak = max(a + b for a, b in zip(sizes, sizes[1:]))
    recommended = int(np.ceil(peak * ARENA_SAFETY_FACTOR / 8192) * 8)  # KB, multiple of 8
    return {
        "flash_kb": round(model_bytes / 1024, 1),
        "arena_lower_bound_kb": round(peak / 1024, 1),
        "arena_recommended_kb": recommended,
    }


def export_model(model: CNN1D, calibration: np.ndarray, out_dir: str | Path,
                 var_name: str = "cnn1d_model", firmware_dir: str = "", log=print) -> dict:
    """Write model.tflite and <var_name>.h to out_dir (and the header to firmware_dir)."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    keras_model = build_keras_model(model.in_channels, model.fc_size)
    delta = transfer_weights(model, keras_model)
    log(f"[export] PyTorch -> Keras weight transfer, max output difference = {delta:.2e}")
    if delta > 1e-3:
        raise RuntimeError(f"Weight transfer mismatch ({delta:.3g}); the Keras model is not equivalent.")

    tflite_bytes = convert_int8(keras_model, calibration)
    tflite_path = out_dir / "model.tflite"
    tflite_path.write_bytes(tflite_bytes)

    header_path = out_dir / f"{var_name}.h"
    header_path.write_text(c_header(tflite_bytes, var_name), newline="\n")
    if firmware_dir:
        Path(firmware_dir).mkdir(parents=True, exist_ok=True)
        (Path(firmware_dir) / f"{var_name}.h").write_text(c_header(tflite_bytes, var_name), newline="\n")

    log(f"[export] INT8 model {len(tflite_bytes) / 1024:.1f} KB -> {tflite_path}")
    return {"tflite_path": str(tflite_path), "header_path": str(header_path),
            "weight_transfer_max_diff": delta, "model_bytes": len(tflite_bytes)}
